version: '3.8'
services:
  redis:
    read_only: true
    restart: always
    image: redis:7.2
    container_name: redis
    ports:
      - '6380:6379'
    networks:
      - bendis
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  users_service:
    restart: always
    container_name: user
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: User
    ports:
      - '5450:5432'
    volumes:
      - UserData:/var/lib/postgresql/data
    networks:
      - bendis
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "root" ]
      interval: 5s
      timeout: 5s
      retries: 5

  product_service:
    restart: always
    container_name: product
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Product
    ports:
      - '5451:5432'
    volumes:
      - ProductData:/var/lib/postgresql/data
    networks:
      - bendis
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "root" ]
      interval: 5s
      timeout: 5s
      retries: 5

  story_service:
    restart: always
    container_name: story
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Story
    ports:
      - '5452:5432'
    volumes:
      - StoryData:/var/lib/postgresql/data
    networks:
      - bendis
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "root" ]
      interval: 5s
      timeout: 5s
      retries: 5

  comment_service:
    restart: always
    container_name: comment
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Comment
    ports:
      - '5453:5432'
    volumes:
      - CommentData:/var/lib/postgresql/data
    networks:
      - bendis
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "root" ]
      interval: 5s
      timeout: 5s
      retries: 5

  cart_service:
    restart: always
    container_name: cart
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Cart
    ports:
      - '5454:5432'
    volumes:
      - CartData:/var/lib/postgresql/data
    networks:
      - bendis
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "root" ]
      interval: 5s
      timeout: 5s
      retries: 5
  order_service:
    restart: always
    container_name: order
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Order
    ports:
      - '5455:5432'
    volumes:
      - OrderData:/var/lib/postgresql/data
    networks:
      - bendis
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "root" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  UserData: { }
  ProductData: { }
  StoryData: { }
  CommentData: { }
  redis_data: { }
  CartData: { }
  OrderData: { }
networks:
  bendis:
    driver: bridge
