services:
  users_service:
    container_name: users
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: User
    ports:
      - '5450:5432'
    volumes:
      - UserData:/var/lib/postgresql/data
  content_service:
    container_name: content
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Content
    ports:
      - '5451:5432'
    volumes:
      - ContentData:/var/lib/postgresql/data

volumes:
  UserData: {}
